# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QTextBrowser, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(499, 624)
        self.frame = QFrame(Widget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 311, 501))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 10, 291, 261))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(140, 100, 16, 20))
        self.label_11 = QLabel(self.frame_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(140, 220, 16, 20))
        self.timun = QLabel(self.frame_2)
        self.timun.setObjectName(u"timun")
        self.timun.setGeometry(QRect(0, 160, 63, 51))
        self.timun.setPixmap(QPixmap(u"images/Timun.png"))
        self.timun.setScaledContents(True)
        self.timun.setWordWrap(False)
        self.label_12 = QLabel(self.frame_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(250, 220, 16, 20))
        self.alpukad = QLabel(self.frame_2)
        self.alpukad.setObjectName(u"alpukad")
        self.alpukad.setGeometry(QRect(230, 150, 51, 61))
        self.alpukad.setPixmap(QPixmap(u"images/Alpukad.png"))
        self.alpukad.setScaledContents(True)
        self.selada = QLabel(self.frame_2)
        self.selada.setObjectName(u"selada")
        self.selada.setGeometry(QRect(0, 40, 63, 61))
        self.selada.setPixmap(QPixmap(u"images/Selada.png"))
        self.selada.setScaledContents(True)
        self.label_13 = QLabel(self.frame_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(120, 0, 41, 20))
        self.kubis = QLabel(self.frame_2)
        self.kubis.setObjectName(u"kubis")
        self.kubis.setGeometry(QRect(110, 150, 63, 61))
        self.kubis.setPixmap(QPixmap(u"images/Kubis.png"))
        self.kubis.setScaledContents(True)
        self.label_9 = QLabel(self.frame_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(250, 100, 16, 20))
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 100, 16, 20))
        self.tomat = QLabel(self.frame_2)
        self.tomat.setObjectName(u"tomat")
        self.tomat.setGeometry(QRect(110, 40, 63, 61))
        self.tomat.setPixmap(QPixmap(u"images/Tomat.png"))
        self.tomat.setScaledContents(True)
        self.label_10 = QLabel(self.frame_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 220, 16, 20))
        self.wortel = QLabel(self.frame_2)
        self.wortel.setObjectName(u"wortel")
        self.wortel.setGeometry(QRect(210, 40, 71, 61))
        self.wortel.setPixmap(QPixmap(u"images/Wortel.png"))
        self.wortel.setScaledContents(True)
        self.label_7 = QLabel(self.frame_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 20, 41, 20))
        self.label_18 = QLabel(self.frame_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(120, 20, 41, 20))
        self.label_19 = QLabel(self.frame_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(230, 20, 41, 20))
        self.label_20 = QLabel(self.frame_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 130, 41, 20))
        self.label_21 = QLabel(self.frame_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(130, 130, 31, 20))
        self.label_22 = QLabel(self.frame_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(230, 130, 51, 20))
        self.frame_3 = QFrame(self.frame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 270, 291, 221))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_14 = QLabel(self.frame_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(120, 0, 51, 20))
        self.label_15 = QLabel(self.frame_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(40, 40, 63, 61))
        self.label_15.setPixmap(QPixmap(u"images/plain.png"))
        self.label_15.setScaledContents(True)
        self.label_16 = QLabel(self.frame_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(190, 40, 63, 61))
        self.label_16.setPixmap(QPixmap(u"images/sm.png"))
        self.label_16.setScaledContents(True)
        self.label_17 = QLabel(self.frame_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(40, 140, 61, 61))
        self.label_17.setPixmap(QPixmap(u"images/oliveoil.png"))
        self.label_17.setScaledContents(True)
        self.saltn = QLabel(self.frame_3)
        self.saltn.setObjectName(u"saltn")
        self.saltn.setGeometry(QRect(190, 140, 63, 71))
        self.saltn.setPixmap(QPixmap(u"images/saltandpepper.png"))
        self.saltn.setScaledContents(True)
        self.label_23 = QLabel(self.frame_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(70, 100, 16, 20))
        self.label_24 = QLabel(self.frame_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(220, 100, 16, 20))
        self.label_25 = QLabel(self.frame_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(70, 200, 16, 20))
        self.label_26 = QLabel(self.frame_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(220, 200, 16, 20))
        self.label_27 = QLabel(self.frame_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(20, 20, 101, 20))
        self.label_28 = QLabel(self.frame_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(170, 20, 101, 20))
        self.label_29 = QLabel(self.frame_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(50, 130, 51, 20))
        self.label_30 = QLabel(self.frame_3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(190, 130, 81, 20))
        self.frame_4 = QFrame(Widget)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(330, 50, 161, 191))
        self.frame_4.setFrameShape(QFrame.Box)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.pushButton_5 = QPushButton(self.frame_4)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(70, 80, 31, 29))
        self.pushButton_10 = QPushButton(self.frame_4)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(60, 140, 31, 29))
        self.pushButton_4 = QPushButton(self.frame_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(10, 80, 31, 29))
        self.pushButton_6 = QPushButton(self.frame_4)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(40, 80, 31, 29))
        self.pushButton_7 = QPushButton(self.frame_4)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(20, 140, 31, 29))
        self.pushButton_13 = QPushButton(self.frame_4)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(120, 140, 31, 29))
        self.pushButton_3 = QPushButton(self.frame_4)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(70, 50, 31, 29))
        self.label = QLabel(self.frame_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 31, 20))
        self.pushButton_2 = QPushButton(self.frame_4)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(40, 50, 31, 29))
        self.pushButton_9 = QPushButton(self.frame_4)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(20, 110, 31, 29))
        self.pushButton = QPushButton(self.frame_4)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 50, 31, 29))
        self.lineEdit = QLineEdit(self.frame_4)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(40, 10, 111, 25))
        self.lineEdit.setReadOnly(True)
        self.pushButton_11 = QPushButton(self.frame_4)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(120, 60, 31, 29))
        self.pushButton_12 = QPushButton(self.frame_4)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(120, 100, 31, 29))
        self.pushButton_8 = QPushButton(self.frame_4)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(60, 110, 31, 29))
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(370, 250, 91, 20))
        self.pushButton_14 = QPushButton(Widget)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(330, 270, 161, 29))
        self.pushButton_15 = QPushButton(Widget)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(10, 520, 311, 91))
        self.pushButton_16 = QPushButton(Widget)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(360, 540, 61, 61))
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(360, 520, 63, 20))
        self.label_5 = QLabel(Widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(110, 530, 101, 41))
        font = QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_6 = QLabel(Widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(60, 570, 211, 20))
        self.textBrowser = QTextBrowser(Widget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(330, 310, 161, 171))

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"2", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"5", None))
        self.timun.setText("")
        self.label_12.setText(QCoreApplication.translate("Widget", u"6", None))
        self.alpukad.setText("")
        self.selada.setText("")
        self.label_13.setText(QCoreApplication.translate("Widget", u"Sayuran", None))
        self.kubis.setText("")
        self.label_9.setText(QCoreApplication.translate("Widget", u"3", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"1", None))
        self.tomat.setText("")
        self.label_10.setText(QCoreApplication.translate("Widget", u"4", None))
        self.wortel.setText("")
        self.label_7.setText(QCoreApplication.translate("Widget", u"Selada", None))
        self.label_18.setText(QCoreApplication.translate("Widget", u"Tomat", None))
        self.label_19.setText(QCoreApplication.translate("Widget", u"Wortel", None))
        self.label_20.setText(QCoreApplication.translate("Widget", u"Timun", None))
        self.label_21.setText(QCoreApplication.translate("Widget", u"Kubis", None))
        self.label_22.setText(QCoreApplication.translate("Widget", u"Alpukad", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"Dressing", None))
        self.label_15.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.saltn.setText("")
        self.label_23.setText(QCoreApplication.translate("Widget", u"A", None))
        self.label_24.setText(QCoreApplication.translate("Widget", u"B", None))
        self.label_25.setText(QCoreApplication.translate("Widget", u"C", None))
        self.label_26.setText(QCoreApplication.translate("Widget", u"D", None))
        self.label_27.setText(QCoreApplication.translate("Widget", u"Plain Mayonnaise", None))
        self.label_28.setText(QCoreApplication.translate("Widget", u"Spicy Mayonnaise", None))
        self.label_29.setText(QCoreApplication.translate("Widget", u"Olive Oil", None))
        self.label_30.setText(QCoreApplication.translate("Widget", u"Salt & Pepper", None))
        self.pushButton_5.setText(QCoreApplication.translate("Widget", u"6", None))
        self.pushButton_10.setText(QCoreApplication.translate("Widget", u"D", None))
        self.pushButton_4.setText(QCoreApplication.translate("Widget", u"4", None))
        self.pushButton_6.setText(QCoreApplication.translate("Widget", u"5", None))
        self.pushButton_7.setText(QCoreApplication.translate("Widget", u"C", None))
        self.pushButton_13.setText(QCoreApplication.translate("Widget", u">", None))
        self.pushButton_3.setText(QCoreApplication.translate("Widget", u"3", None))
        self.label.setText(QCoreApplication.translate("Widget", u"Saldo", None))
        self.pushButton_2.setText(QCoreApplication.translate("Widget", u"2", None))
        self.pushButton_9.setText(QCoreApplication.translate("Widget", u"A", None))
        self.pushButton.setText(QCoreApplication.translate("Widget", u"1", None))
        self.pushButton_11.setText(QCoreApplication.translate("Widget", u"<", None))
        self.pushButton_12.setText(QCoreApplication.translate("Widget", u"x", None))
        self.pushButton_8.setText(QCoreApplication.translate("Widget", u"B", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"Masukkan Uang", None))
        self.pushButton_14.setText("")
        self.pushButton_15.setText("")
        self.pushButton_16.setText("")
        self.label_3.setText(QCoreApplication.translate("Widget", u"Kembalian", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"P U L L", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Please open it when the light is flashing", None))
        self.textBrowser.setHtml(QCoreApplication.translate("Widget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Petunjuk Penggunaan:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">1. Masukkan uang dengan nominal 5.000, 10.000, dan 20.000, batas maksimum saldo senilai 40.000 dan minimum 15.000</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-"
                        "left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">2. Pilih sayuran yang diinginkan dengan memilih angka yang sudah tersedia</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">3. Pilih dressing yang diinginkan dengan memilih huruf yang sudah tersedia</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">4. Ambil salad dan kembalian di tempat yang telah tersedia</span></p></body></html>", None))
    # retranslateUi

